spring:
  profiles:
    active: dev #The default is the development environment

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #Request header stored by JWT
  secret: mall-portal-secret #The key used by JWT encryption and decryption
  expiration: 604800 #JWT overdue time(60*60*24*7)
  tokenHead: Bearer  #Get the beginning in the JWT load

secure:
  ignored:
    urls: #Safe path whitelist
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**

# Custom redis key
redis:
  database: mall
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # Verification code expiration time
    common: 86400 # 24 hours

# Message queue definition
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue

