spring:
  application:
    name: mall-search
  profiles:
    active: dev #The default is the development environment

server:
  port: 8081

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml



