spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #Connection pool initialization size
      min-idle: 10 #Minimum idle connections
      max-active: 20 #Maximum number of connections
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #Exclusions this type of data
      stat-view-servlet: #Login user name and password to access the monitoring webpage
        login-username: druid
        login-password: druid
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300 # es connection address and port number
      cluster-name: elasticsearch # The name of the es cluster